/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_accounts__account_id__get"];
        /** Update Account */
        put: operations["update_account_api_accounts__account_id__put"];
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_accounts__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_accounts__account_id__snapshots_get"];
        put?: never;
        /** Create Snapshot */
        post: operations["create_snapshot_api_accounts__account_id__snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Snapshot */
        delete: operations["delete_snapshot_api_accounts__account_id__snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/computed-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Computed Balance
         * @description Return the current balance using: latest snapshot + transactions after snapshot date.
         */
        get: operations["computed_balance_api_accounts__account_id__computed_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        /**
         * Create Transaction
         * @description Create a manual transaction.
         */
        post: operations["create_transaction_api_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transaction Meta
         * @description Return available filter options for the transactions page.
         */
        get: operations["transaction_meta_api_transactions_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_transactions_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/detect-transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Internal Transfers
         * @description Detect pairs of transactions that are likely internal transfers between accounts.
         */
        post: operations["detect_internal_transfers_api_transactions_detect_transfers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Delete Transactions
         * @description Delete multiple transactions at once.
         */
        post: operations["bulk_delete_transactions_api_transactions_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/bulk-update-transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Transfer
         * @description Mark/unmark multiple transactions as internal transfers.
         */
        post: operations["bulk_update_transfer_api_transactions_bulk_update_transfer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/bulk-update-reviewed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Reviewed
         * @description Mark multiple transactions as reviewed (or unreviewed) at once.
         */
        post: operations["bulk_update_reviewed_api_transactions_bulk_update_reviewed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/bulk-update-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Category
         * @description Update category for multiple transactions at once.
         */
        post: operations["bulk_update_category_api_transactions_bulk_update_category_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Transactions */
        get: operations["export_transactions_api_transactions_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_transactions__transaction_id__get"];
        /** Update Transaction */
        put: operations["update_transaction_api_transactions__transaction_id__put"];
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_api_categories__category_id__get"];
        /** Update Category */
        put: operations["update_category_api_categories__category_id__put"];
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_categories__category_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescan Categories
         * @description Re-apply all category rules to all non-manually-reviewed transactions.
         */
        post: operations["rescan_categories_api_categories_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/rules/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Rule
         * @description Return transactions matching the given conditions (for rule preview).
         */
        post: operations["preview_rule_api_categories_rules_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/rules/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Rules */
        get: operations["list_all_rules_api_categories_rules_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{category_id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_categories__category_id__rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_categories__category_id__rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Rule */
        put: operations["update_rule_api_categories_rules__rule_id__put"];
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_categories_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/rules/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Rules
         * @description Merge multiple rules into one. All conditions are combined. Uses the first rule's category/priority/account.
         */
        post: operations["merge_rules_api_categories_rules_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect */
        post: operations["detect_api_upload_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/parse-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Preview
         * @description Parse CSV and return all transactions with auto-assigned categories for review.
         */
        post: operations["parse_preview_api_upload_parse_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/save-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Profile
         * @description Save or update a bank profile from the column mapping UI.
         */
        post: operations["save_profile_api_upload_save_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_upload_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** By Category */
        get: operations["by_category_api_analytics_by_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/spending-trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spending Trends
         * @description Return monthly spending per category for trend charts.
         */
        get: operations["spending_trends_api_analytics_spending_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cash Flow */
        get: operations["cash_flow_api_analytics_cash_flow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net Worth History */
        get: operations["net_worth_history_api_analytics_net_worth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recurring */
        get: operations["recurring_api_analytics_recurring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Budget Table
         * @description Return monthly budget table: last N months of actuals + saved forecasts.
         */
        get: operations["budget_table_api_analytics_budget_get"];
        /**
         * Upsert Budget Entry
         * @description Create or update a budget entry for a category+month+account.
         */
        put: operations["upsert_budget_entry_api_analytics_budget_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/budget-full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Budget Full
         * @description Return structured budget table with income, fixed expenses, and variable expenses.
         */
        get: operations["budget_full_api_analytics_budget_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ml/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_ml_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ml/suggest-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest Rules */
        get: operations["suggest_rules_api_ml_suggest_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ml/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train */
        post: operations["train_api_ml_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bank-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bank Profiles */
        get: operations["list_bank_profiles_api_bank_profiles_get"];
        put?: never;
        /** Create Bank Profile */
        post: operations["create_bank_profile_api_bank_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bank-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bank Profile */
        get: operations["get_bank_profile_api_bank_profiles__profile_id__get"];
        /** Update Bank Profile */
        put: operations["update_bank_profile_api_bank_profiles__profile_id__put"];
        post?: never;
        /** Delete Bank Profile */
        delete: operations["delete_bank_profile_api_bank_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investment Accounts
         * @description Return all investment accounts with their snapshot history and computed metrics.
         */
        get: operations["investment_accounts_api_investments_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/total-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investment Total Series
         * @description Monthly aggregated series across all investment accounts.
         *     For each month, sum the latest-known value of each account up to that month.
         */
        get: operations["investment_total_series_api_investments_total_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountBalanceSnapshotCreate */
        AccountBalanceSnapshotCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount Cents */
            amount_cents: number;
            /**
             * Contribution Cents
             * @default 0
             */
            contribution_cents: number;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Notes */
            notes?: string | null;
        };
        /** AccountBalanceSnapshotOut */
        AccountBalanceSnapshotOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount Cents */
            amount_cents: number;
            /**
             * Contribution Cents
             * @default 0
             */
            contribution_cents: number;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Account Id */
            account_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AccountCreate */
        AccountCreate: {
            /** Name */
            name: string;
            /** Bank Name */
            bank_name: string;
            /**
             * Account Type
             * @default courant
             */
            account_type: string;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
        };
        /** AccountOut */
        AccountOut: {
            /** Name */
            name: string;
            /** Bank Name */
            bank_name: string;
            /**
             * Account Type
             * @default courant
             */
            account_type: string;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name?: string | null;
            /** Bank Name */
            bank_name?: string | null;
            /** Account Type */
            account_type?: string | null;
            /** Currency */
            currency?: string | null;
            /** Color */
            color?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** AnalyticsSummary */
        AnalyticsSummary: {
            /** Total Income Cents */
            total_income_cents: number;
            /** Total Expenses Cents */
            total_expenses_cents: number;
            /** Net Cash Flow Cents */
            net_cash_flow_cents: number;
            /** Net Worth Cents */
            net_worth_cents: number;
            /** Total Income Display */
            total_income_display: string;
            /** Total Expenses Display */
            total_expenses_display: string;
            /** Net Cash Flow Display */
            net_cash_flow_display: string;
            /** Net Worth Display */
            net_worth_display: string;
            /** Last Transaction Date */
            last_transaction_date?: string | null;
        };
        /** BankProfileCreate */
        BankProfileCreate: {
            /** Name */
            name: string;
            /** Column Mapping */
            column_mapping: {
                [key: string]: unknown;
            };
            /**
             * Date Format
             * @default %d/%m/%Y
             */
            date_format: string;
            /**
             * Encoding
             * @default utf-8
             */
            encoding: string;
            /**
             * Delimiter
             * @default ;
             */
            delimiter: string;
            /** Detection Fingerprint */
            detection_fingerprint?: {
                [key: string]: unknown;
            } | null;
        };
        /** BankProfileOut */
        BankProfileOut: {
            /** Name */
            name: string;
            /** Column Mapping */
            column_mapping: {
                [key: string]: unknown;
            };
            /**
             * Date Format
             * @default %d/%m/%Y
             */
            date_format: string;
            /**
             * Encoding
             * @default utf-8
             */
            encoding: string;
            /**
             * Delimiter
             * @default ;
             */
            delimiter: string;
            /** Detection Fingerprint */
            detection_fingerprint?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
        };
        /** BankProfileUpdate */
        BankProfileUpdate: {
            /** Name */
            name?: string | null;
            /** Column Mapping */
            column_mapping?: {
                [key: string]: unknown;
            } | null;
            /** Date Format */
            date_format?: string | null;
            /** Encoding */
            encoding?: string | null;
            /** Delimiter */
            delimiter?: string | null;
            /** Detection Fingerprint */
            detection_fingerprint?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_confirm_api_upload_confirm_post */
        Body_confirm_api_upload_confirm_post: {
            /** File */
            file: string;
            /** Account Id */
            account_id: number;
            /** Profile Id */
            profile_id?: number | null;
            /** Column Mapping */
            column_mapping?: string | null;
            /** Date Format */
            date_format?: string | null;
            /** Encoding */
            encoding?: string | null;
            /** Delimiter */
            delimiter?: string | null;
            /** Category Overrides */
            category_overrides?: string | null;
            /** Force Import Hashes */
            force_import_hashes?: string | null;
        };
        /** Body_detect_api_upload_detect_post */
        Body_detect_api_upload_detect_post: {
            /** File */
            file: string;
        };
        /** Body_parse_preview_api_upload_parse_preview_post */
        Body_parse_preview_api_upload_parse_preview_post: {
            /** File */
            file: string;
            /** Profile Id */
            profile_id?: number | null;
            /** Column Mapping */
            column_mapping?: string | null;
            /** Date Format */
            date_format?: string | null;
            /** Encoding */
            encoding?: string | null;
            /** Delimiter */
            delimiter?: string | null;
        };
        /** BudgetFullResponse */
        BudgetFullResponse: {
            /** Months */
            months: string[];
            /** Sections */
            sections: components["schemas"]["BudgetSectionRow"][];
            reste_row: components["schemas"]["BudgetTableRow"];
            grand_total_row: components["schemas"]["BudgetTableRow"];
            /** Account Id */
            account_id?: number | null;
        };
        /** BudgetSectionRow */
        BudgetSectionRow: {
            /** Section */
            section: string;
            /** Section Label */
            section_label: string;
            /** Rows */
            rows: components["schemas"]["BudgetTableRow"][];
            section_totals: components["schemas"]["BudgetTableRow"];
        };
        /** BudgetTableCell */
        BudgetTableCell: {
            /** Month */
            month: string;
            /** Actual Cents */
            actual_cents: number;
            /** Expected Cents */
            expected_cents: number;
        };
        /** BudgetTableResponse */
        BudgetTableResponse: {
            /** Months */
            months: string[];
            /** Rows */
            rows: components["schemas"]["BudgetTableRow"][];
            /** Column Totals Actual */
            column_totals_actual: number[];
            /** Column Totals Expected */
            column_totals_expected: number[];
        };
        /** BudgetTableRow */
        BudgetTableRow: {
            /** Category Id */
            category_id: number | null;
            /** Category Name */
            category_name: string;
            /** Category Color */
            category_color: string;
            /**
             * Is Investment
             * @default false
             */
            is_investment: boolean;
            /** Cells */
            cells: components["schemas"]["BudgetTableCell"][];
            /** Total Actual Cents */
            total_actual_cents: number;
            /** Total Expected Cents */
            total_expected_cents: number;
        };
        /** BulkCategoryUpdate */
        BulkCategoryUpdate: {
            /** Ids */
            ids: number[];
            /** Category Id */
            category_id?: number | null;
        };
        /** BulkDeleteQuery */
        BulkDeleteQuery: {
            /** Ids */
            ids: number[];
        };
        /** BulkReviewUpdate */
        BulkReviewUpdate: {
            /** Ids */
            ids: number[];
            /**
             * Is Manually Reviewed
             * @default true
             */
            is_manually_reviewed: boolean;
        };
        /** BulkTransferUpdate */
        BulkTransferUpdate: {
            /** Ids */
            ids: number[];
            /**
             * Is Internal Transfer
             * @default true
             */
            is_internal_transfer: boolean;
        };
        /** CashFlowMonth */
        CashFlowMonth: {
            /** Month */
            month: string;
            /** Income Cents */
            income_cents: number;
            /** Expenses Cents */
            expenses_cents: number;
            /** Net Cents */
            net_cents: number;
        };
        /** CategoryBreakdown */
        CategoryBreakdown: {
            /** Category Id */
            category_id: number | null;
            /** Category Name */
            category_name: string;
            /** Total Cents */
            total_cents: number;
            /** Count */
            count: number;
            /** Percentage */
            percentage: number;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Color
             * @default #94a3b8
             */
            color: string;
            /**
             * Icon
             * @default tag
             */
            icon: string;
            /**
             * Is Income
             * @default false
             */
            is_income: boolean;
            /** Expense Type */
            expense_type?: string | null;
            /**
             * Is Investment
             * @default false
             */
            is_investment: boolean;
            /** Account Id */
            account_id?: number | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Color
             * @default #94a3b8
             */
            color: string;
            /**
             * Icon
             * @default tag
             */
            icon: string;
            /**
             * Is Income
             * @default false
             */
            is_income: boolean;
            /** Expense Type */
            expense_type?: string | null;
            /**
             * Is Investment
             * @default false
             */
            is_investment: boolean;
            /** Account Id */
            account_id?: number | null;
            /** Id */
            id: number;
        };
        /** CategoryRuleCreate */
        CategoryRuleCreate: {
            /**
             * Conditions
             * @default []
             */
            conditions: components["schemas"]["RuleCondition"][];
            /** Category Id */
            category_id: number;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Account Id */
            account_id?: number | null;
            /**
             * Logic Operator
             * @default AND
             */
            logic_operator: string;
        };
        /** CategoryRuleOut */
        CategoryRuleOut: {
            /**
             * Conditions
             * @default []
             */
            conditions: components["schemas"]["RuleCondition"][];
            /** Category Id */
            category_id: number;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Account Id */
            account_id?: number | null;
            /**
             * Logic Operator
             * @default AND
             */
            logic_operator: string;
            /** Id */
            id: number;
        };
        /** CategoryRuleUpdate */
        CategoryRuleUpdate: {
            /** Conditions */
            conditions?: components["schemas"]["RuleCondition"][] | null;
            /** Category Id */
            category_id?: number | null;
            /** Priority */
            priority?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Account Id */
            account_id?: number | null;
            /** Logic Operator */
            logic_operator?: string | null;
        };
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
            /** Is Income */
            is_income?: boolean | null;
            /** Expense Type */
            expense_type?: string | null;
            /** Is Investment */
            is_investment?: boolean | null;
            /** Account Id */
            account_id?: number | null;
        };
        /** ConfirmResponse */
        ConfirmResponse: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MLStatus */
        MLStatus: {
            /** Trained */
            trained: boolean;
            /** Last Trained */
            last_trained: string | null;
            /** Sample Count */
            sample_count: number | null;
            /** Accuracy */
            accuracy: number | null;
        };
        /** MLTrainResponse */
        MLTrainResponse: {
            /** Accuracy */
            accuracy: number;
            /** Sample Count */
            sample_count: number;
        };
        /** MergeRulesRequest */
        MergeRulesRequest: {
            /** Rule Ids */
            rule_ids: number[];
            /**
             * Logic Operator
             * @default OR
             */
            logic_operator: string;
        };
        /** RecurringTransaction */
        RecurringTransaction: {
            /** Description */
            description: string;
            /** Occurrences */
            occurrences: number;
            /** Avg Amount Cents */
            avg_amount_cents: number;
            /**
             * Last Date
             * Format: date
             */
            last_date: string;
            /** Category Id */
            category_id: number | null;
        };
        /** RuleCondition */
        RuleCondition: {
            /** Field */
            field: string;
            /** Operator */
            operator: string;
            /** Value */
            value: string;
        };
        /** RulePreviewRequest */
        RulePreviewRequest: {
            /** Conditions */
            conditions: components["schemas"]["RuleCondition"][];
            /** Account Id */
            account_id?: number | null;
            /**
             * Logic Operator
             * @default AND
             */
            logic_operator: string;
        };
        /** TransactionCreateManual */
        TransactionCreateManual: {
            /** Account Id */
            account_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Is Debit */
            is_debit: boolean;
            /** Balance After Cents */
            balance_after_cents?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** TransactionMeta */
        TransactionMeta: {
            /** Available Months */
            available_months: string[];
            /** Available Banks */
            available_banks: string[];
        };
        /** TransactionOut */
        TransactionOut: {
            /** Account Id */
            account_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /** Amount Cents */
            amount_cents: number;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Category Id */
            category_id?: number | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Is Debit */
            is_debit: boolean;
            /** Balance After Cents */
            balance_after_cents?: number | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Is Manually Reviewed
             * @default false
             */
            is_manually_reviewed: boolean;
            /**
             * Is Internal Transfer
             * @default false
             */
            is_internal_transfer: boolean;
            /** Import Hash */
            import_hash: string;
            /** Import Batch Id */
            import_batch_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Amount Display */
            amount_display?: string | null;
            /** Account Name */
            account_name?: string | null;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Category Id */
            category_id?: number | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Notes */
            notes?: string | null;
            /** Is Manually Reviewed */
            is_manually_reviewed?: boolean | null;
            /** Is Internal Transfer */
            is_internal_transfer?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"][];
                };
            };
        };
    };
    create_account_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_api_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_accounts__account_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_accounts__account_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalanceSnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_api_accounts__account_id__snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountBalanceSnapshotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalanceSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_api_accounts__account_id__snapshots__snapshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    computed_balance_api_accounts__account_id__computed_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: {
                account_id?: number | null;
                category_id?: number | null;
                uncategorized?: boolean | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
                is_debit?: boolean | null;
                is_internal_transfer?: boolean | null;
                bank_name?: string | null;
                month?: string | null;
                import_batch_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreateManual"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transaction_meta_api_transactions_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionMeta"];
                };
            };
        };
    };
    list_batches_api_transactions_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    detect_internal_transfers_api_transactions_detect_transfers_post: {
        parameters: {
            query?: {
                max_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_transactions_api_transactions_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_transfer_api_transactions_bulk_update_transfer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTransferUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_reviewed_api_transactions_bulk_update_reviewed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkReviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_category_api_transactions_bulk_update_category_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transactions_api_transactions_export_get: {
        parameters: {
            query?: {
                account_id?: number | null;
                category_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_transactions__transaction_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_api_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_categories__category_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_categories__category_id__delete: {
        parameters: {
            query?: {
                replace_with_id?: number | null;
            };
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_categories_api_categories_rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    preview_rule_api_categories_rules_preview_post: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_rules_api_categories_rules_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleOut"][];
                };
            };
        };
    };
    list_rules_api_categories__category_id__rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_categories__category_id__rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_categories_rules__rule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_categories_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_rules_api_categories_rules_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRulesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_api_upload_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_detect_api_upload_detect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_preview_api_upload_parse_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_preview_api_upload_parse_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_api_upload_save_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_upload_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_confirm_api_upload_confirm_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_analytics_summary_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                account_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    by_category_api_analytics_by_category_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                account_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryBreakdown"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spending_trends_api_analytics_spending_trends_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                account_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_flow_api_analytics_cash_flow_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                account_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashFlowMonth"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    net_worth_history_api_analytics_net_worth_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                account_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recurring_api_analytics_recurring_get: {
        parameters: {
            query?: {
                account_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringTransaction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_table_api_analytics_budget_get: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_budget_entry_api_analytics_budget_put: {
        parameters: {
            query: {
                category_id: number;
                month: string;
                expected_amount_cents: number;
                account_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_full_api_analytics_budget_full_get: {
        parameters: {
            query?: {
                year?: number;
                account_id?: number | null;
                account_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetFullResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_ml_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLStatus"];
                };
            };
        };
    };
    suggest_rules_api_ml_suggest_rules_get: {
        parameters: {
            query?: {
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_api_ml_train_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLTrainResponse"];
                };
            };
        };
    };
    list_bank_profiles_api_bank_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankProfileOut"][];
                };
            };
        };
    };
    create_bank_profile_api_bank_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bank_profile_api_bank_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bank_profile_api_bank_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bank_profile_api_bank_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investment_accounts_api_investments_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    investment_total_series_api_investments_total_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
